### PR TITLE
[ACCSEC-33208] - Size Artifact iOS Framework

### PR DESCRIPTION
**Pull request by AlejandroOrozco**
## Ticket

- [33208] - Size Artifact iOS Framework.
- [33523] - iOS Demo App Firebase Distribution.

## Description
- Add Size Artifact for iOS Framework
- Distribute Demo App through Firebase

## Commit message
- [33208] - Size Artifact iOS Framework.
- [33523] - iOS Demo App Firebase Distribution.

## Testing
- [ ] Added unit tests
- [ ] Ran unit tests successfully
- [ ] Added documentation for public APIs and/or Wiki

### CODE REVIEW

**Review by ferazoguerrero — APPROVED** [review]

**Comment by AlejandroOrozco** [comment]
> @AlejandroOrozco For verify push, there are two values: compressed and uncompressed, what is the difference with the value reported here?

Basically, `compressed` refers to when it is in its IPA state. All IPA files are just compressed binaries of the applications. `Uncompressed` refers to what we are using for this. We can report both values without any issue, but I think the uncompressed size is more precise.

**Comment by SergioFierro** [comment]
Can you change to `dev` as the base branch?

**Comment by yafuquen** [comment]
> > @AlejandroOrozco For verify push, there are two values: compressed and uncompressed, what is the difference with the value reported here?
> 
> Basically, `compressed` refers to when it is in its IPA state. All IPA files are just compressed binaries of the applications. `Uncompressed` refers to what we are using for this. We can report both values without any issue, but I think the uncompressed size is more precise.

So, if I understood correctly, compressed will be the impact to the IPA (download from appstore?) and uncompressed will be the impact in the device, correct? I can think of times were customers were worried about the download size (IPA, compressed?) and also the installation size (uncompressed?), so it could be helpful to have both. Also, it could be interesting to know the impact for compressed and the percentage, to see if the zip process is reducing the percentage compared to uncompressed

**Comment by yafuquen** [comment]
> > > @AlejandroOrozco For verify push, there are two values: compressed and uncompressed, what is the difference with the value reported here?
> > 
> > 
> > Basically, `compressed` refers to when it is in its IPA state. All IPA files are just compressed binaries of the applications. `Uncompressed` refers to what we are using for this. We can report both values without any issue, but I think the uncompressed size is more precise.
> 
> So, if I understood correctly, compressed will be the impact to the IPA (download from appstore?) and uncompressed will be the impact in the device, correct? I can think of times were customers were worried about the download size (IPA, compressed?) and also the installation size (uncompressed?), so it could be helpful to have both. Also, it could be interesting to know the impact for compressed and the percentage, to see if the zip process is reducing the percentage compared to uncompressed

To be improved in a future task

**Comment by SergioFierro** [comment]
> Can you change to `dev` as the base branch?

Ping!

**Review by SergioFierro — APPROVED** [review]

**Pull request merged**
